#please note : no '-' is used
kafka:
   bootstrapServers: |
      localhost:9092
   bootstrapServersTarget: |
      localhost:9093
   zookeeperHost: localhost
   defaultKeySerde: String
   defaultValueSerde: Avro
   appVersion: 312 #This will define the version
   zkNodeUpd: true
   appDeltaValue: 200
   appSmallDeltaValue: 100
   appSleepTimeMs: 10
   autoOffsetReset: earliest
   schemaRegistyUrl: http://192.168.56.101:8081/
   numConsumerThreads: 2
   topics:
      input-topics: input-topic-5,input-topic-6
   topicsFields:
#       input-topic-1: insert_dt
#       input-topic-2: upd_dt
      input-topic-1: default
      input-topic-2: default